version: "3.9"

services:
  crudapp:
    image: crudapp
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - DB_URL=mongodb://mongo:27017/crudappdb
      - HOST=0.0.0.0
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
